namespace MatrixIO.IO.MpegTs
{
    public enum StreamIdentifier : byte
    {
        ProgramStreamMap = 0xBC,
        PrivateStream1 = 0xBD,
        PaddingStream = 0xBE,
        PrivateStream2 = 0xBF,
        #region Numbered Audio Streams
        AudioStream0 = 0xC0,
        AudioStream1 = 0xC1,
        AudioStream2 = 0xC2,
        AudioStream3 = 0xC3,
        AudioStream4 = 0xC4,
        AudioStream5 = 0xC5,
        AudioStream6 = 0xC6,
        AudioStream7 = 0xC7,
        AudioStream8 = 0xC8,
        AudioStream9 = 0xC9,
        AudioStream10 = 0xCA,
        AudioStream11 = 0xCB,
        AudioStream12 = 0xCC,
        AudioStream13 = 0xCD,
        AudioStream14 = 0xCE,
        AudioStream15 = 0xCF,
        AudioStream16 = 0xD0,
        AudioStream17 = 0xD1,
        AudioStream18 = 0xD2,
        AudioStream19 = 0xD3,
        AudioStream20 = 0xD4,
        AudioStream21 = 0xD5,
        AudioStream22 = 0xD6,
        AudioStream23 = 0xD7,
        AudioStream24 = 0xD8,
        AudioStream25 = 0xD9,
        AudioStream26 = 0xDA,
        AudioStream27 = 0xDB,
        AudioStream28 = 0xDC,
        AudioStream29 = 0xDD,
        AudioStream30 = 0xDE,
        AudioStream31 = 0xDF,
        #endregion
        #region Numbered Video Streams
        VideoStream0 = 0xE0,
        VideoStream1 = 0xE1,
        VideoStream2 = 0xE2,
        VideoStream3 = 0xE3,
        VideoStream4 = 0xE4,
        VideoStream5 = 0xE5,
        VideoStream6 = 0xE6,
        VideoStream7 = 0xE7,
        VideoStream8 = 0xE8,
        VideoStream9 = 0xE9,
        VideoStream10 = 0xEA,
        VideoStream11 = 0xEB,
        VideoStream12 = 0xEC,
        VideoStream13 = 0xED,
        VideoStream14 = 0xEE,
        VideoStream15 = 0xEF,
        #endregion
        EcmStream = 0xF0,
        EmmStream = 0xF1,
        DsmCcStream = 0xF2,
        Iso13522Stream = 0xF3,
        TypeAStream = 0xF4,
        TypeBStream = 0xF5,
        TypeCStream = 0xF6,
        TypeDStream = 0xF7,
        TypeEStream = 0xF8,
        AncillaryStream = 0xF9,
        SlPacketizedStream = 0xFA,
        FlexMuxStream = 0xFB,
        // 0xFC-0xFE RESERVED
        ProgramStreamDirectory = 0xFF,
    }
}
